(library
 (name ocaml_lsp_e2e_tests)
 (libraries async core expect_test_helpers_async ocaml_lsp_fiber lev_fiber_async lsp lsp_fiber lsp_json_rpc_types ocaml_lsp_fiber_shims ocaml_lsp_test_lib ocaml_lsp_server spawn unix yojson)
 (inline_tests
 (flags (-verbose))
  (deps %{exe:../../bin/main.exe}))
 (flags (:standard -open Lsp_json_rpc_types -alert -private_lsp_library -open Lev_fiber_async))
 (preprocess (pps ppx_let ppx_expect -no-locations-check -expect-test-strict-indentation=false)))
