(library
 (name ocaml_lsp_server)

  (libraries async base cmarkit core core_unix dyn ocaml_lsp_fiber lev_fiber_async ocaml_lsp_lrgrep_shim lsp lsp_fiber lsp_json_rpc_types merlin-lib.analysis merlin-lib.commands merlin-lib.dot_protocol merlin-lib.extend merlin-lib.kernel merlin-lib.ocaml_parsing merlin-lib.ocaml_preprocess merlin-lib.query_commands merlin-lib.query_protocol merlin-lib.ocaml_merlin_specific merlin-lib.utils  ocaml_lsp_stdune merlin-lib.ocaml_utils merlin-lib.ocaml_typing ocaml_lsp_misc_shims ocaml_lsp_fiber_shims ocaml_lsp_css_lsp ocaml_lsp_dune_integration  file_path ocaml_lsp_logging ocaml_lsp_metrics ocaml_lsp_remote_lsp ocaml_lsp_uri ocaml_lsp_version ocamlc-loc compiler-libs.common odoc-parser ordering ppx_string priority_lsp_executor_lib re re2 spawn stage core_unix.time_float_unix unix yojson)
 (preprocess (pps ppx_let ppx_log ppx_compare ppx_yojson_conv -no-locations-check ppx_expect ppx_sexp_conv ppx_here ppx_sexp_message))
 (flags (:standard -open Cmarkit -open Lsp_json_rpc_types -alert -private_lsp_library -open Lev_fiber_async -open Ocaml_preprocess -open Query_protocol -open Query_commands -open Ppx_yojson_conv_lib.Yojson_conv -alert -unstable -w -60)))
