open Import

type init =
  | Uninitialized
  | Initialized of
      { params : InitializeParams.t
      ; workspaces : Workspaces.t
      ; exp_client_caps : Client.Experimental_capabilities.t
      ; diagnostics : Diagnostics.t
      ; dune_subscriptions : Dune_subscriptions.t
      ; manage_dune_connection : Fiber.Cancel.t
      ; position_encoding : [ `UTF16 | `UTF8 ]
      }

type hover_extended = { mutable history : (Uri.t * Position.t * int) option }

type t =
  { store : Document_store.t
  ; merlin : Document.Single_pipeline.t
  ; merlin_config : Merlin_config.DB.t
  ; init : init
  ; detached : Fiber.Pool.t
  ; configuration : Configuration.t
  ; trace : TraceValue.t
  ; ocamlformat_rpc : Ocamlformat_rpc.t
  ; symbols_thread : Lev_fiber.Thread.t Lazy_fiber.t
  ; wheel : Lev_fiber.Timer.Wheel.t
  ; hover_extended : hover_extended
  ; feature_id : Feature_id.t option (* Required in remote-lsp RPCs. *)
  ; mutable remote_lsp_available : bool
  ; mutable event_index : int
  ; mutable logging_session : Ocaml_lsp_logging.t option
  ; worker_name : string option
  (** Logical name of this ocaml-lsp worker, as passed via [-worker-name]. Included in
      logs and threaded into [Ocaml_lsp_logging.init] so that every log management system
      entry and every structured logging row can be attributed to the worker that emitted
      it. *)
  }

let create
  ~store
  ~merlin
  ~detached
  ~configuration
  ~ocamlformat_rpc
  ~symbols_thread
  ~wheel
  ~worker_name
  =
  { init = Uninitialized
  ; merlin_config = Merlin_config.DB.create ()
  ; store
  ; merlin = Document.Single_pipeline.create merlin
  ; detached
  ; configuration
  ; trace = Off
  ; ocamlformat_rpc
  ; symbols_thread
  ; wheel
  ; hover_extended = { history = None }
  ; feature_id = None
  ; remote_lsp_available = true (* Attempt to fall back until we learn we can't. *)
  ; event_index = 0
  ; logging_session = None
  ; worker_name
  }
;;

let wheel t = t.wheel

let decide_event_index (t : t) ~event_index =
  (* Use the [event_index] generated by [ocaml-lsp-wrapper] when present; otherwise fall
     back to our local counter. *)
  match event_index with
  | Some event_index ->
    t.event_index <- event_index;
    event_index
  | None ->
    t.event_index <- t.event_index + 1;
    t.event_index
;;

let initialize_params (state : t) =
  match state.init with
  | Uninitialized -> assert false
  | Initialized init -> init.params
;;

let workspaces (state : t) =
  match state.init with
  | Uninitialized -> assert false
  | Initialized init -> init.workspaces
;;

let workspace_root t =
  match t.init with
  | Uninitialized -> assert false
  | Initialized init ->
    (match init.params.rootUri with
     | None -> assert false
     | Some uri -> uri)
;;

let position_encoding t =
  match t.init with
  | Uninitialized -> assert false
  | Initialized init -> init.position_encoding
;;

let diagnostics t =
  match t.init with
  | Uninitialized -> assert false
  | Initialized init -> init.diagnostics
;;

let dune_subscriptions t =
  match t.init with
  | Uninitialized -> None
  | Initialized init -> Some init.dune_subscriptions
;;

let initialize
  t
  ~position_encoding
  ~dune_subscriptions
  ~manage_dune_connection
  (params : InitializeParams.t)
  workspaces
  diagnostics
  =
  assert (t.init = Uninitialized);
  { t with
    init =
      Initialized
        { params
        ; workspaces
        ; diagnostics
        ; dune_subscriptions
        ; manage_dune_connection
        ; position_encoding
        ; exp_client_caps =
            Client.Experimental_capabilities.of_opt_json params.capabilities.experimental
        }
  }
;;

let modify_workspaces t ~f =
  let init =
    match t.init with
    | Uninitialized -> assert false
    | Initialized init -> Initialized { init with workspaces = f init.workspaces }
  in
  { t with init }
;;

let client_capabilities t = (initialize_params t).capabilities

let experimental_client_capabilities t =
  match t.init with
  | Uninitialized -> assert false
  | Initialized { exp_client_caps; _ } -> exp_client_caps
;;

let log_msg server ~type_ ~message =
  let state = Server.state server in
  task_if_running state.detached ~f:(fun () ->
    let log = LogMessageParams.create ~type_ ~message in
    Server.notification server (Server_notification.LogMessage log))
;;

(* extracts editor name and version *)
let get_editor (t : t) =
  match t.init with
  | Uninitialized -> "unknown (uninitialized)", "unknown"
  | Initialized s ->
    (match s.params.clientInfo with
     | None -> "unknown (no clientInfo)", "unknown"
     | Some i -> InitializeParams.get_editor i)
;;

let editor_is_vscode (t : t) =
  let editor_name, _ = get_editor t in
  String.is_prefix (String.lowercase editor_name) ~prefix:"vscode"
;;

let should_fall_back (t : t) =
  Configuration.remote_lsp_fallback_enabled t.configuration && t.remote_lsp_available
;;

let stage t = t.configuration.stage
