name: Test

on:
  pull_request:
    branches:
      - internal

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4"

      - name: Run build
        run: make buildoss

      - name: Run tests
        run: make runtestoss AUTOCONF=autoconf
